version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: always
    environment:
      DOMAINS: 'dockertest.com -> http://web:8000'
      STAGE: local
    volumes:
      - ssl-certs:/var/lib/https-portal
  web:
    image: nginx:1.15.6
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    command: [nginx, '-g', 'daemon off;']
  app:
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  ssl-certs:
  db-data:
  redis-data: